# ===========================#
# General Site Config
# ===========================#

title: Erizo
email: chilewich@gmail.com
description: >-
  A Journal of the Arts is a bilingual publication of new poetry and visual art
  from the Americas. Un diario de las artes publica nuerva poesía y arte de las
  Américas.
baseurl: ""
url: "http://erizo.siteleaf.net"
github_username:  erizo_mag

markdown: kramdown

plugins:
  - jekyll-feed

sass:
  sass_dir: _lib
  style: compressed

collections:
  issues:
    collection_dir: _issues
    output: true

defaults:
  -scope:
    path: ""
    type: "issues"
  values:
    layout: "issue_detail"

# ===========================#
# File Inclusions/Exclusions
# ===========================#
#
exclude:
  - Gemfile
  - Gemfile.lock
