---
title: Erizo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  issues:
    collection_dir: _issues
    output: true
defaults:
- scope:
    path: ''
    type: "issues"
  values:
    layout: "issue_detail"
email: chilewich@gmail.com
description: 'A Journal of the Arts is a bilingual publication of new poetry and visual
  art from the Americas. Un diario de las artes publica nuerva poesía y arte de las
  Américas.

'
baseurl: ''
github_username: erizo_mag
permalink: "/"
markdown: kramdown
plugins:
- jekyll-feed
- github-pages
sass:
  sass_dir: _lib
  style: compressed
