---
title: Erizo
timezone: UTC
collections:
  contributors:
    title: Contributors
    output: true
  issues:
    title: Issues
    output: true
    collection_dir: _issues
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: issues
  values:
    layout: issue_detail
email: chilewich@gmail.com
description: 'A Journal of the Arts is a bilingual publication of new poetry and visual
  art from the Americas. Un diario de las artes publica nuerva poesía y arte de las
  Américas.

'
baseurl: 
github_username: erizo_mag
store_url: https://erizo.bigcartel.com
permalink: "/"
markdown: kramdown
plugins:
- jekyll-feed
- github-pages
sass:
  sass_dir: _lib
  style: compressed
site_description_en: a journal publishing new poetry and visual art from the Americas
site_description_es: un diario publicando nueva poesía y arte de las Américas
splash_introduction: 'A selection of works from the first issue of Erizo: Biquini
  Wax EPS, Mónica de la Torre, Daniel Saldaña París, Alejandra Prieto, Fernando Palma,
  Jessica O. Marsh, and Tatiana Lipkes.'
footer_column_1:
  title: About Erizo
  description: Erizo publishes new poetry and visual art from the Americas.
footer_column_2:
  title: Submission and Contact
  description: |-
    To submit poems or visual art, or to inquire about translating, please email us at editors@erizoerizo.com. We are also interested
    collaborations between poets and artists.
site_copyright: Copyright Erizo, 2017-2019. All Rights Reserved.
