title: Erizo
email: chilewich@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A Journal of the Arts is a bilingual publication of new poetry and visual art
  from the Americas. Un diario de las artes publica nuerva poesía y arte de las
  Américas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erizo.siteleaf.net"
github_username:  erizo_mag

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _lib
  style: compressed

collections:
  issues:
    collection_dir: issues
    output: true
    permalink: /:collection/:name

defaults:
  -scope:
    path: ""
    type: "issues"
  values:
    layout: "issue_detail"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
