---
title: Erizo
<<<<<<< HEAD
timezone: UTC
=======
email: chilewich@gmail.com
description: >
  A Journal of the Arts is a bilingual publication of new poetry and visual art
  from the Americas. Un diario de las artes publica nuerva poesía y arte de las
  Américas.
baseurl: ""
github_username:  erizo_mag

markdown: kramdown

plugins:
  - jekyll-feed
  - github-pages

sass:
  sass_dir: _lib
  style: compressed

>>>>>>> gh-pages
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
<<<<<<< HEAD
=======

defaults:
  -scope:
    path: ""
    type: "issues"
  values:
    layout: "issue_detail"
>>>>>>> gh-pages
