---
title: Erizo
timezone: UTC
collections:
  contributors:
    title: Contributors
    output: true
  issues:
    title: Issues
    output: true
    collection_dir: _issues
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: issues
  values:
    layout: issue_detail
email: chilewich@gmail.com
description: 'A Journal of the Arts is a bilingual publication of new poetry and visual
  art from the Americas. Un diario de las artes publica nuerva poesía y arte de las
  Américas.

'
baseurl: 
github_username: erizo_mag
store_url: https://erizo.bigcartel.com
permalink: "/"
markdown: kramdown
plugins:
- jekyll-feed
- github-pages
sass:
  sass_dir: _lib
  style: compressed
site_description_en: a journal of the arts publishes new poetry and visual art from
  the Americas.
site_description_es: un diario de las artes publica nueva poesísia y arte de las Américas
